### ISSUE TITLE
Implement get_closest()

### ISSUE THREAD

**Issue by carrieklc** [UBC-MDS/pydistrrr#19]
As a user, I want to know which point(s) are closest to a target point based on a specified distance metric. I want to know the single closest point, or multiple top k closest points. These closest points should be returned as indices so I can access them from the dataframe in which they exist.

Acceptance Criteria
* The function should return a list of indices corresponding to observations that are closest in distance to a specified observation
* The function should return a k-length list of indices if the input dataframe is at least the size of k
* The function should throw error/exception for error parameters

**Comment by MikeYuanMY** [comment]
tests passed, merged to master
