### ISSUE TITLE
add information to __init__.py and setup.py

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/pydistrrr#22]
Regarding Varada's post, add some information to `setup.py` and `__init__.py`

1. Exactly what to include in the `setup.py` file? Are these parameters essential to the function of the package or just descriptive?
--> `setup.py` is basically the build script for `setuptools`, which lets us easily download, build, install, upgrade, and uninstall Python packages. The things you put in `setup.py` is the metadata about your package (its name, version etc) which is used by `setuptools`. This may seem like ‘optional’ information. But it is important to include this information for your package. This info will be shown when you do `pip show <package_name>`, for example.

2. What to include in the `__init__.py` file?
`__init__.py` is used to initialize your package and it is invoked when the package is imported (i.e., when you do `import` in your code). Some examples of initialization code could be importing some modules that all functions in your code use or loading some large data files that are used by your functions. For example, suppose my package is a spelling correction package and I need to load a dictionary of English words for my approach. It might be better to load it in `__init__.py` rather than loading it every time the corresponding function is called. This way the dictionary is loaded only once when the package is imported. Note that in old Python versions the existence of this file was required. But starting with Python 3.3, you can create packages without any `__init__.py`. Of course, it can still be present if any initialization is needed.

**Comment by EvanYathon** [comment]
Currently I am planning to `import pandas as pd` in `__init__.py`.  Let me know if there are any other things you'd like added in to `__init__.py` and I can throw 'em in there.

**Comment by carrieklc** [comment]
Evan, if you haven't done this already, could you add numpy? I've also been referring to functions in numpy as np so might need to do `import numpy as np` to keep it working, although I won't remove my import statement just yet.

**Comment by EvanYathon** [comment]
Will do.  Should have that PR request sent in the next bit here.

**Comment by carrieklc** [comment]
Addressed this issue in our above referenced commit - package now set up with appropriate files to support installation via pip.
