### ISSUE TITLE
Update documentation in README based on milestone 1 feedback

### ISSUE THREAD

**Issue by carrieklc** [UBC-MDS/pydistrrr#25]
Address README-related feedback items brought up in #11 - this includes ensuring we're more precise about using Python-specific data structures (e.g. lists rather than vectors), clarifying function descriptions, and fixing typos. 

Feedback related to comments and other code-embedded documentation are outside the scope of this issue. Those items will be addressed under their associated features.

**Comment by MikeYuanMY** [comment]
merged
