### ISSUE TITLE
Feedback on milestone 2

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/pydistrrr#32]
Good job on your package!, it was easy to install and the functions work as specified.

Here are some points where you can improve:

- You need to add example usage for every function. Since you didn’t have examples of the usage for all functions I had to go to the functions to find out what the names of the arguments were and how to use them. 

- Get_distance has the argument metric, while get_all_distances has the argument dist. These should be consistent. 

- In your description of the function, the order of the description should be the order in which I put the arguments of the function. So for example, for get_all_distances I tried putting the data frame first (since it was the first described input), and it didn’t work unless I wrote data =.

- Filter_distances is empty. 

- In get_closest, if top_k is greater than the number of rows in the data frame it doesn’t say anything. (maybe it should give a warning?)

**Comment by MikeYuanMY** [comment]
the empty filter_distance issue is addressed in dbc8d352794081fdd9448d0f9eee1c462b369952

**Comment by carrieklc** [comment]
* Added example usages for all functions in README in 7cf4a9b48f604183ab68cd8c009b42fc82f154d8

* Made changes to use "metric" consistently as the distance parameter across functions in 34ed9fdffe1145a9b59640f4f1239bd450283a8c and 8548a9da3a30840e63eacc2b5058b2787a8d8149

* Updated the order of input parameters listed in function descriptions to be consistent with how functions can be called in 63d7ed6abb1910106653c883883d0e240d6adb16

* Added a warning message to user if top_k is greater than the number of rows in the data frame when calling `get_closest()` in 9a58d445498945a716f32542424087cff1ef7004

**Comment by carrieklc** [comment]
Feedback has been addressed per above - closing issue. Thanks!
