### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/pydistrrr#4]
Great job with the proposal!.

I really like the table with the functions, it is very clear and the descriptions are well done. 

- For the description of get_closest, I would like to see a brief description of what you will do when you have ties. For example if you want the 5 closest values, but the distances of 5 and 6 are the same (let me know if this is not clear). 

- In the Alignment with Python / R Ecosystems, I would like to know if and where your functions will be different from the current functions, or will your functions just be wrappers around currently existing functions.

**Comment by carrieklc** [comment]
Hi Melissa, thank you for the feedback. We've updated our READMEs to address the issues you brought up. You can find those changes in these commits: 
https://github.com/UBC-MDS/pydistrrr/commit/9bc030b3967c759de1a3d191ad330e059a80fd60
https://github.com/UBC-MDS/distrrr/commit/1a25765c8b49ea953fd06e241df59aa816abaaa4
